### ISSUE TITLE
misnamed field when adding security group

### ISSUE THREAD

**Issue by slapplebags** [ucsb-eri/guam#35]
the group name is labelled as the "Username" field, it should be labelled "Group Name" or similar:
https://guam.grit.ucsb.edu/secgroups
![Screenshot from 2024-12-10 16-16-26](https://github.com/user-attachments/assets/b2b2d5bb-86dd-4cf0-bdaf-828d9cecb274)

**Comment by tjaartvdwalt** [comment]
Fixed this in #33, but only released it now
